name: Build Supermodel

on:
  workflow_dispatch:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt install -y \
            build-essential \
            libsdl2-dev \
            libsdl2-net-dev \
            libglu1-mesa-dev \
            libgl1-mesa-dev

      - name: Build Supermodel
        run: |
          make -f Makefiles/Makefile.UNIX clean
          make -f Makefiles/Makefile.UNIX TARGET=Supermodel -j$(nproc) || true
          echo "🧪 Conteúdo da pasta bin/:"
          find ./bin -type f -exec ls -lh {} \;
          echo "🧪 Procurando qualquer coisa com 'supermodel' no nome:"
          find . -type f -iname '*supermodel*'

      - name: Upload All Binaries (debug)
        uses: actions/upload-artifact@v4
        with:
          name: full-bin-dump
          path: |
            bin/
            obj/
            Src/
            Makefiles/
