name: Build Supermodel

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Install Dependencies
      run: |
        sudo apt update
        sudo apt install -y libsdl2-dev libsdl2-net-dev build-essential

    - name: Build Supermodel
      run: |
        make -f Makefiles/Makefile.UNIX -j$(nproc)

    - name: Upload Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: Supermodel-linux-build
        path: bin/Supermodel  # Ajuste conforme o nome final do binário
