name: Build Supermodel

on:
  workflow_dispatch:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt install -y \
            build-essential \
            libsdl2-dev \
            libsdl2-net-dev \
            libglu1-mesa-dev \
            libgl1-mesa-dev

      - name: Build Supermodel
        run: |
          make -f Makefiles/Makefile.UNIX clean
          make -f Makefiles/Makefile.UNIX TARGET=Supermodel -j$(nproc)

      - name: Upload Supermodel Binary
        uses: actions/upload-artifact@v4
        with:
          name: supermodel-linux
          path: bin/Supermodel
