name: Build Supermodel

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt install -y build-essential libsdl2-dev libsdl2-net-dev

      - name: Build Supermodel
        run: |
          make -f Makefiles/Makefile.UNIX -j$(nproc)

      - name: Upload Binary
        uses: actions/upload-artifact@v4
        with:
          name: supermodel-linux
          path: bin/Supermodel
