name: Build Supermodel

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Install Dependencies
      run: |
        sudo apt update
        sudo apt install -y libsdl2-dev libsdl2-net-dev build-essential

    - name: Build Supermodel
      run: |
        make -f Makefiles/Makefile.UNIX -j$(nproc)

    - name: Upload Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: Supermodel-linux-build
        path: Supermodel  # Especifica o binário final, ajuste conforme o nome gerado!
